### ISSUE TITLE
update sa-simulation dependency to 2.1.1

### ISSUE THREAD

**Issue by jamie-cunningham** [act3-ace/run-time-assurance#11]
The sa-simulation package has a critical fix in version 2.1.1. Update the dependency.

**Comment by keatincf** [comment]
The jax library version will conflict.  I'm not sure if there was a reason that the library was pinned to a specific version

**Comment by jamie-cunningham** [comment]
> The jax library version will conflict. I'm not sure if there was a reason that the library was pinned to a specific version

Yeah I'm hitting that. Not sure about the pinning either but regardless this package has some other required updates for this upgrade.

**Comment by jamie-cunningham** [comment]
We also need to introduce some real tests for this package.

**Comment by jamie-cunningham** [comment]
Updating to 2.1.2 for JIT hotfix
